float_prec:
- low
- high

cuda_compiler_version:
- None
#- 9.2
#- 10.0
- 10.1
- 11.0
- 11.1
cudnn:
- undefined
#- 7
#- 7
- 7
- 8
- 8
cdt_name:
- cos7
#- cos7
#- cos7
- cos7
- cos7
- cos7
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
#- quay.io/condaforge/linux-anvil-cuda:9.2 
#- quay.io/condaforge/linux-anvil-cuda:10.0 
- quay.io/condaforge/linux-anvil-cos7-cuda:10.1 
- quay.io/condaforge/linux-anvil-cuda:11.0 
- quay.io/condaforge/linux-anvil-cuda:11.1 
zip_keys:
  - - cudnn
    - cuda_compiler_version
    - docker_image
    - cdt_name
  - - python
    - python_impl
    - numpy
c_compiler_version:
- 8
cxx_compiler_version:
- 8
channel_sources:
- deepmodeling,https://deepmodeling.njzjz.win,nvidia,defaults
channel_targets:
- deepmodeling dev
python:
- 3.7.*
- 3.8.*
- 3.9.*
python_impl:
- cpython
- cpython
- cpython
numpy:
- 1.20
- 1.20
- 1.20
