dp_variant:
- cpu
- gpu
float_prec:
- low
- high
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
c_compiler_version:
- 4  # [osx]
cxx_compiler_version:
- 4  # [osx]
cudatoolkit:
- 10.1
tf_version:
- 2.1
