{% set name = "deepmd-kit" %}
{% set version = "2.0.0.b3" %}
{% set py = environ.get('CONDA_PY', '') %}

{% set tf_version = "2.5.0" %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}

{% else %}
{% set dp_variant = "gpu" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v{{ version }}

build:
  number: 1
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}"  # [float_prec == 'high']
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}_{{float_prec}}"  # [float_prec != 'high']
  script_env:
    - DP_VARIANT=cuda  # [cuda_compiler_version != 'None'] 
    - DP_FLOAT_PREC=low  # [float_prec != 'high']
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [unix]
    - "pip install . --no-deps -vv"  # [win]
  skip: true  # [osx and cuda_compiler_version != 'None']
  skip: true  # [not linux]
  skip: true  # [py>=38 and cuda_compiler_version == '9.2' ]
  skip: true  # [py>=38 and cuda_compiler_version == '10.0' ]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - numpy
    - setuptools_scm
    - tensorflow-base {{ tf_version }}* mkl*  # [cuda_compiler_version == 'None']
    - tensorflow-base {{ tf_version }}* gpu* # [cuda_compiler_version != 'None']
    - cudatoolkit {{ cuda_compiler_version }}*  # [cuda_compiler_version != 'None']
    - scikit-build
    - m2r
    - dargs
    - pyyaml

  run:
    - python
    - numpy
    - scipy
    - tensorflow-base {{ tf_version }}* mkl*  # [cuda_compiler_version == 'None']
    - tensorflow-base {{ tf_version }}* gpu* # [cuda_compiler_version != 'None']
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}*  # [cuda_compiler_version != 'None']
    - dargs
    - pyyaml

test:
  imports:
    - deepmd
  commands:
    - dp -h

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
