{% set name = "deepmd-kit" %}
{% set version = "1.1.3" %}
{% set py = environ.get('CONDA_PY', '') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: 984ef69fbf9cecae80de91ac7c2126e0e22398e5
  patches:
  - low_prec.diff  # [float_prec == 'low']
  - osx.patch  # [osx]

build:
  number: 0
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_{{ dp_variant }}"  # [float_prec == 'high']
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_{{ dp_variant }}_{{float_prec}}"  # [float_prec != 'high']
  script:
    - "SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv"  # [unix]
    - "set SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%"  # [win]
    - "pip install . --no-deps -vv"  # [win]
  skip: true  # [py<35]
  skip: true  # [osx and dp_variant == 'gpu']
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - numpy >=1.13.3,<2.0a0
    - setuptools_scm
    - tensorflow  # [dp_variant != 'gpu']
    - tensorflow-gpu  # [dp_variant == 'gpu']
    - cudatoolkit {{ cudatoolkit }}*  # [dp_variant == 'gpu']
    - setuptools_scm
    - scikit-build
    - m2r

  run:
    - python
    - numpy
    - scipy
    - {{ pin_compatible('tensorflow', max_pin='x.x') }}  # [dp_variant != 'gpu']
    - {{ pin_compatible('tensorflow-gpu', max_pin='x.x') }}  # [dp_variant == 'gpu']
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}*  # [dp_variant == 'gpu']

test:
  imports:
    - deepmd
  commands:
    - dp -h

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
