{% set name = "deepmd-kit" %}
{% set version = "2.0.1" %}
{% set py = environ.get('CONDA_PY', '') %}

{% set tf_version = "2.5.0" %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}

{% else %}
{% set dp_variant = "gpu" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v{{ version }}

build:
  number: 0
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}"
  script_env:
    - DP_VARIANT=cuda  # [cuda_compiler_version != 'None'] 
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [unix]
    - "pip install . --no-deps -vv"  # [win]
  skip: true  # [osx and cuda_compiler_version != 'None']
  skip: true  # [ppc64le and cuda_compiler_version == 'None']
  skip: true  # [not linux]
  skip: true  # [ppc64le and not py==38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  >=3.7
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - numpy
    - setuptools_scm
    - tensorflow-base {{ tf_version }}* mkl*  # [cuda_compiler_version == 'None']
    - tensorflow-base {{ tf_version }}* gpu* # [cuda_compiler_version != 'None']
    - cudatoolkit {{ cuda_compiler_version }}*  # [cuda_compiler_version != 'None']
    - scikit-build
    - m2r
    - dargs
    - pyyaml
    - python-hostlist

  run:
    - python
    - numpy
    - scipy
    - tensorflow-base {{ tf_version }}* mkl*  # [cuda_compiler_version == 'None']
    - tensorflow-base {{ tf_version }}* gpu* # [cuda_compiler_version != 'None']
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}*  # [cuda_compiler_version != 'None']
    - dargs
    - pyyaml
    - python-hostlist

test:
  imports:
    - deepmd
  #requires:
  #  - pip
  commands:
    - dp -h
    - dp --version
    #- pip check

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
