{% set name = "deepmd-kit" %}
{% set version = "2.2.8" %}
{% set py = environ.get('CONDA_PY', '') %}


{% set tf_version = "2.9" %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}
{% set tf_variant = "cpu" %}

{% else %}
{% set dp_variant = "gpu" %}
{% set tf_variant = "cuda" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v{{ version }}

build:
  number: 0
  string: "py{{ py }}_{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}"
  script_env:
    - DP_VARIANT=cuda  # [cuda_compiler_version != 'None'] 
  script:
    - "{{ PYTHON }} -m pip install . -vv"  # [unix]
    - "pip install . --no-deps -vv"  # [win]
  skip: true  # [osx and cuda_compiler_version != 'None']
  skip: true  # [ppc64le and cuda_compiler_version == 'None']
  skip: true  # [not linux]
  skip: true  # [ppc64le and not py==38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != 'None']
    - cmake  >=3.23
    - make  # [unix]
    - ninja

  host:
    - python
    - pip
    - setuptools_scm
    - tensorflow {{ tf_version }}.* {{ tf_variant }}*
    - scikit-build-core
    - hatch-fancy-pypi-readme

  run:
    - python
    - numpy
    - scipy
    - tensorflow {{ tf_version }}.* {{ tf_variant }}*
    - dargs >=0.3.5
    - pyyaml
    - python-hostlist >=1.21
    - h5py
    - wcmatch
    - packaging

test:
  imports:
    - deepmd
  requires:
    - pip
  commands:
    - dp -h
    - dp --version
    #- pip check

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
