appveyor:
  secure:
    BINSTAR_TOKEN: +Hbd0iE86bSYV3CLG1jtSfPeH6NZsLlppZxPpON+etrZMnP1boqGfGGbOYP+HyGa
github:
  user_or_org: deepmd-kit-recipes
channels:
  targets:
    -
      - deepmodeling
channel_priority: flexible
  #provider:
  #  linux_ppc64le: azure
test_on_native_only: true
azure:
  free_disk_space: True